sudo: required
dist: trusty

language:
  cpp

git:
  submodules: false

compiler:
  #- clang # 3.5.0
  - gcc # 4.8.4

install:
    # Install dependencies
    - sudo apt-get update -qq
    - sudo apt-get install -qy build-essential cmake libeigen3-dev libboost-all-dev libgflags-dev git ninja

before_script:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule sync
  - git submodule init && git submodule update
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release
    -DSPC_ENABLE_INSTALL=ON 
    -DCMAKE_BUILD_TYPE=Release 
    -DCMAKE_INSTALL_PREFIX="/installed"
    -DSPC_BUILD_SHARED=ON 
    -DSPC_INSTALL_LIB_DIR="lib"
    ..

script:
  # We use only 4 core because gcc and clang can be memory hungry
  - make -j2